# Generated by Django 5.2.13 on 2026-04-23 17:39

import apps.service.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Seri No')),
                ('family', models.CharField(choices=[('4K', '4K Kamera'), ('8K', '8K Kamera'), ('TZOOM', 'T-Zoom'), ('SSFORCE', 'SuperSpectral Force'), ('OTHER', 'Diğer')], max_length=32, verbose_name='Cihaz Ailesi')),
                ('model_name', models.CharField(blank=True, max_length=128, verbose_name='Model Adı')),
                ('customer_name', models.CharField(blank=True, max_length=256, verbose_name='Müşteri Adı')),
                ('customer_contact', models.CharField(blank=True, max_length=256, verbose_name='Müşteri İletişim')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'Cihazlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Arıza Kategorisi',
                'verbose_name_plural': 'Arıza Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Parça Kodu')),
                ('name', models.CharField(max_length=256, verbose_name='Parça Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Parça',
                'verbose_name_plural': 'Parçalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=16, unique=True, verbose_name='Servis Kodu')),
                ('subject', models.CharField(max_length=256, verbose_name='Konu')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('root_cause', models.TextField(blank=True, verbose_name='Kök Neden')),
                ('resolution_steps', models.TextField(blank=True, verbose_name='Çözüm Adımları')),
                ('verification_passed', models.BooleanField(blank=True, null=True, verbose_name='Doğrulama Geçti')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Doğrulama Notları')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='normal', max_length=16, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('investigating', 'İnceleniyor'), ('waiting_part', 'Parça Bekleniyor'), ('in_progress', 'İşlemde'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı')], default='new', max_length=32, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapatılma')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='service.device', verbose_name='Cihaz')),
                ('fault_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='service.faultcategory', verbose_name='Arıza Kategorisi')),
                ('parts_used', models.ManyToManyField(blank=True, related_name='tickets', to='service.part', verbose_name='Kullanılan Parçalar')),
            ],
            options={
                'verbose_name': 'Servis Kaydı',
                'verbose_name_plural': 'Servis Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.service.models.attachment_upload_path, verbose_name='Dosya')),
                ('kind', models.CharField(choices=[('video', 'Video'), ('photo', 'Fotoğraf'), ('pdf', 'PDF'), ('log', 'Log')], max_length=16, verbose_name='Tür')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Başlık')),
                ('original_name', models.CharField(max_length=256, verbose_name='Orijinal Dosya Adı')),
                ('size_bytes', models.BigIntegerField(verbose_name='Boyut (byte)')),
                ('mime_type', models.CharField(blank=True, max_length=128, verbose_name='MIME Tipi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Zamanı')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service.serviceticket', verbose_name='Servis Kaydı')),
            ],
            options={
                'verbose_name': 'Ek Dosya',
                'verbose_name_plural': 'Ek Dosyalar',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Belirti')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptoms', to='service.faultcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Belirti',
                'verbose_name_plural': 'Belirtiler',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='symptom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='service.symptom', verbose_name='Belirti'),
        ),
        migrations.CreateModel(
            name='HistoricalServiceTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=16, verbose_name='Servis Kodu')),
                ('subject', models.CharField(max_length=256, verbose_name='Konu')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('root_cause', models.TextField(blank=True, verbose_name='Kök Neden')),
                ('resolution_steps', models.TextField(blank=True, verbose_name='Çözüm Adımları')),
                ('verification_passed', models.BooleanField(blank=True, null=True, verbose_name='Doğrulama Geçti')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Doğrulama Notları')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='normal', max_length=16, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('investigating', 'İnceleniyor'), ('waiting_part', 'Parça Bekleniyor'), ('in_progress', 'İşlemde'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı')], default='new', max_length=32, verbose_name='Durum')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncelleme')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapatılma')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.device', verbose_name='Cihaz')),
                ('fault_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.faultcategory', verbose_name='Arıza Kategorisi')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('symptom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.symptom', verbose_name='Belirti')),
            ],
            options={
                'verbose_name': 'historical Servis Kaydı',
                'verbose_name_plural': 'historical Servis Kayıtları',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Yorum')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Dahili Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service.serviceticket', verbose_name='Servis Kaydı')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['created_at'],
            },
        ),
    ]
