# Generated by Django 5.2.13 on 2026-04-24 07:33

import apps.knowledge.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalKnowledgeArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=280, verbose_name='Slug')),
                ('summary', models.TextField(verbose_name='Özet')),
                ('solution_body', models.TextField(verbose_name='Çözüm Rehberi')),
                ('verification_checklist', models.TextField(blank=True, verbose_name='Doğrulama Listesi')),
                ('device_family', models.CharField(choices=[('4K', '4K Kamera'), ('8K', '8K Kamera'), ('TZOOM', 'T-Zoom'), ('SSFORCE', 'SuperSpectral Force'), ('OTHER', 'Diğer')], max_length=32, verbose_name='Cihaz Ailesi')),
                ('tags', models.CharField(blank=True, max_length=256, verbose_name='Etiketler')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('review', 'İncelemede'), ('published', 'Yayında'), ('archived', 'Arşiv')], default='draft', max_length=16, verbose_name='Durum')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versiyon')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Zamanı')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncelleme')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('fault_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.faultcategory', verbose_name='Arıza Kategorisi')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_ticket', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.serviceticket', verbose_name='Kaynak Ticket')),
                ('symptom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.symptom', verbose_name='Belirti')),
            ],
            options={
                'verbose_name': 'historical Makale',
                'verbose_name_plural': 'historical Makaleler',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(verbose_name='Özet')),
                ('solution_body', models.TextField(verbose_name='Çözüm Rehberi')),
                ('verification_checklist', models.TextField(blank=True, verbose_name='Doğrulama Listesi')),
                ('device_family', models.CharField(choices=[('4K', '4K Kamera'), ('8K', '8K Kamera'), ('TZOOM', 'T-Zoom'), ('SSFORCE', 'SuperSpectral Force'), ('OTHER', 'Diğer')], max_length=32, verbose_name='Cihaz Ailesi')),
                ('tags', models.CharField(blank=True, max_length=256, verbose_name='Etiketler')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('review', 'İncelemede'), ('published', 'Yayında'), ('archived', 'Arşiv')], default='draft', max_length=16, verbose_name='Durum')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versiyon')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_articles', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('fault_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='service.faultcategory', verbose_name='Arıza Kategorisi')),
                ('source_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='service.serviceticket', verbose_name='Kaynak Ticket')),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='service.symptom', verbose_name='Belirti')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.knowledge.models.article_attachment_upload_path, verbose_name='Dosya')),
                ('kind', models.CharField(choices=[('video', 'Video'), ('photo', 'Fotoğraf'), ('pdf', 'PDF'), ('log', 'Log')], max_length=16, verbose_name='Tür')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Başlık')),
                ('original_name', models.CharField(max_length=256, verbose_name='Orijinal Dosya Adı')),
                ('size_bytes', models.BigIntegerField(verbose_name='Boyut (byte)')),
                ('mime_type', models.CharField(blank=True, max_length=128, verbose_name='MIME Tipi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='knowledge.knowledgearticle', verbose_name='Makale')),
            ],
            options={
                'verbose_name': 'Ek Dosya',
                'verbose_name_plural': 'Ek Dosyalar',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
